set mouse=a
execute pathogen#infect()
set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins
colorscheme luna
set encoding=utf8

set expandtab tabstop=2 shiftwidth=2 softtabstop=2
set pastetoggle=<F3>

set laststatus=2
set noshowmode

hi CursorLine term=bold cterm=bold ctermbg=8
set cursorline

vmap <C-v> c<ESC>"+p
imap <C-v> <ESC>"+pi

let g:airline_theme='luna'
