execute pathogen#infect()
set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins
colorscheme luna
"nmap <silent> <C-D> :NERDTreeToggle<CR>
map <C-n> :NERDTreeToggle<CR>
set encoding=utf8
let g:airline_powerline_fonts = 1
set guifont=Meslo\ LG\ M\ for\ Powerline\ 10
"
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
       let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline_theme = 'kalisi'
set t_Co=256

"close vim if only nerdtree is open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"autocmd vimenter * NERDTree | wincmd p

let g:webdevicons_conceal_nerdtree_brackets = 0

let g:airline#extensions#whitespace#show_message = 1

set tabstop=2 shiftwidth=2 expandtab
