set mouse=a
execute pathogen#infect()
set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins
colorscheme luna
set encoding=utf8

set expandtab tabstop=2 shiftwidth=2 softtabstop=2

"autodetect paste
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction

set laststatus=2
set noshowmode

hi CursorLine term=bold cterm=bold ctermbg=8
set cursorline

vmap <C-v> c<ESC>"+p
imap <C-v> <ESC>"+pi

let g:airline_theme='luna'
