#!/bin/bash

# udev will wait for our script to finish before the monitor is available
# for use, so we will use the `at` command to run our command again as
# another user:
if [ "$1" != "forked" ]; then
    #echo "$(dirname $0)/$(basename $0) forked" | at now
    echo "$(dirname $0)/$(basename $0) forked"
fi

# udev runs as root, so we need to tell it how to connect to the X server:
export DISPLAY=:0
export XAUTHORITY=/home/matthieu/.Xauthority

# Find out the device path to our graphics card:
cardPath=/sys$(udevadm info -q path -n /dev/dri/card0)

# Detect if the monitor is connected and, if so, the monitor's ID:
conHdmi=$(xrandr | sed -n '/HDMI-1 connected/p')
shaHdmi=$(sha1sum $cardPath/card0-HDMI-A-1/edid | cut -f1 -d " ")

# The useful part: check what the connection status is, and run some other commands
if [ -n "$conHdmi" ]; then
    if [ "$shaHdmi" = "d2ff52bcb1caa50a63fef3ffa307d0acbb1e64dd" ]; then    # Office PC
        xrandr --output eDP-1 --auto --output HDMI-1 --auto --left-of eDP-1
    else                                            # Probably a projector
        xrandr --output eDP-1 --auto --output HDMI-1 --auto --same-as eDP-1
    fi
else
    xrandr --output eDP-1 --auto --output HDMI-1 --off
fi
